[package]
name = "mikumarimaker"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "defenestrator"

[dependencies]
rust_ringitem_format = "0.1.2"
frib_datasource = "0.3.0"
clap = "4.5.58"

[dev-dependencies]
rand = "0.10.0"